log:
  level: WARN

api:
  insecure: true
  dashboard: true

ping: {}

providers:
  docker:
    exposedByDefault: false
    network: traefik-net
  file:
    filename: "/etc/traefik/dynamic.yaml"
    watch: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

