log:
  level: DEBUG

api:
  insecure: true

providers:
  docker:
    exposedbydefault: false

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

certificatesresolvers:
  pebble:
    acme:
#      tlsChallenge: true
#      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      caServer: "https://pebble:14000/dir"
      email: "admin@traefik.local"
      storage: "/letsencrypt/acme.json"
      httpchallenge:
        entrypoint: "http"
